spring.application.name=Shippix-Java

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/shippix
spring.datasource.username=postgres
spring.datasource.password=postgrespass
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT SecretKey
jwt.secret=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBmb3IgSldUIEhhc2hpbmc=

logging.level.org.springframework.security=DEBUG
