spring.application.name=Shippix-Java

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Shippix
spring.datasource.username=postgres
spring.datasource.password=root123

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect